# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: twitter.com/jianqing
google_plus: https://plus.google.com/117530512676606671516
fb_admins:
fb_app_id:
weibo: http://weibo.com/u/2230140707