# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     redcarpet
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
title: 简庆的blog
subTitle: 记录工作和生活中的成长点滴
description: 这里是简庆的blog，用来记录我的工作和生活，特别是在前端开发方面。
url: http://woaixiangbao.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 作品
    url: /works.html
  - text: 联系我
    url: http://woaixiangbao.github.io/contact.html
  - text: 博客源代码
    url: https://github.com/woaixiangbao/woaixiangbao.github.io

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: https://plus.google.com/117530512676606671516
  - class: fa-facebook
    url: https://www.facebook.com/qing.jian.58
  - class: fa-github
    url: http://github.com/woaixiangbao
  - class: fa-weibo
    url: http://weibo.com/2230140707
  - class: fa-renren
    url: http://woaixiangbao.github.io
  - class: fa-pinterest
    url: http://woaixiangbao.github.io
  - class: fa-twitter
    url: https://twitter.com/jianqing
  - class: fa-rss
    url: http://woaixiangbao.github.io

#作者信息
author:
  link: http://http://woaixiangbao.github.io/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: jianqing

duoshuo:
  config: false
