# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: 简庆的博客
subtitle: "记录有关前端的一些知识"
email: blessjq@gmail.com
name: jian qing
description: >- # this means to ignore newlines until "baseurl:"
 jianqing's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://woaixiangbao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
cover: "/images/cover.jpg"
logo: "/images/logo.jpg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: jianqing

# Google analytics
ga_tracking_id: "UA-61690079-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: javascript
    desc: "有关JavaScript的一切"

  - cat: css
    desc: "有关css的一切"

  - cat: html
    desc: "有关html的一切"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true

social:
  - name: Twitter
    icon: twitter
    username: jianqing
    url: https://twitter.com/jianqing
    desc: Follow me on Twitter
    share: true
  - name: Facebook
    icon: facebook
    username: 简庆
    url: http://www.facebook.com/blessjq
    desc: Friend me on Facebook
    share: true
  - name: GitHub
    icon: github
    username: jianqing
    url: https://github.com/woaixiangbao
    desc: Fork me on GitHub
    share: false

  


